# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packages/protos/users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'packages/protos/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpackages/protos/users.proto\x12\x05users\"H\n\x0bUserMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x11\n\x0fGetUsersRequest\"5\n\x10GetUsersResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.users.UserMessage\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x13GetUserByIdResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage\"5\n\x11\x43reateUserRequest\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage\"6\n\x12\x43reateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage\"5\n\x11UpdateUserRequest\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage\"6\n\x12UpdateUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\x12\x44\x65leteUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.users.UserMessage2\xdd\x02\n\x05Users\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packages.protos.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERMESSAGE']._serialized_start=38
  _globals['_USERMESSAGE']._serialized_end=110
  _globals['_GETUSERSREQUEST']._serialized_start=112
  _globals['_GETUSERSREQUEST']._serialized_end=129
  _globals['_GETUSERSRESPONSE']._serialized_start=131
  _globals['_GETUSERSRESPONSE']._serialized_end=184
  _globals['_GETUSERBYIDREQUEST']._serialized_start=186
  _globals['_GETUSERBYIDREQUEST']._serialized_end=218
  _globals['_GETUSERBYIDRESPONSE']._serialized_start=220
  _globals['_GETUSERBYIDRESPONSE']._serialized_end=275
  _globals['_CREATEUSERREQUEST']._serialized_start=277
  _globals['_CREATEUSERREQUEST']._serialized_end=330
  _globals['_CREATEUSERRESPONSE']._serialized_start=332
  _globals['_CREATEUSERRESPONSE']._serialized_end=386
  _globals['_UPDATEUSERREQUEST']._serialized_start=388
  _globals['_UPDATEUSERREQUEST']._serialized_end=441
  _globals['_UPDATEUSERRESPONSE']._serialized_start=443
  _globals['_UPDATEUSERRESPONSE']._serialized_end=497
  _globals['_DELETEUSERREQUEST']._serialized_start=499
  _globals['_DELETEUSERREQUEST']._serialized_end=530
  _globals['_DELETEUSERRESPONSE']._serialized_start=532
  _globals['_DELETEUSERRESPONSE']._serialized_end=586
  _globals['_USERS']._serialized_start=589
  _globals['_USERS']._serialized_end=938
# @@protoc_insertion_point(module_scope)
